learning_log/learning_log/urls.py
# from django.urls import path
from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    # path(r'^admin/', admin.site.urls),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include(('users.urls', 'users'), namespace='users')),
    url(r'', include(('learning_logs.urls', 'learning_logs'), namespace='learning_logs')),
]

learning_log/learning_logs/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),                                          # Home page
    url(r'^topics/$', views.topics, name='topics'),                                 # All topics
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),                 # Requested topic
    url(r'^new_topic/$', views.new_topic, name='new_topic'),                        # Page of creating a new topic
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),      # Create new entry
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),   # Edit entry
]

learning_log/users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views


urlpatterns = [
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
]

learning_log/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    """Тема, которую изучает пользователь"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Возвращает строковое представление модели."""
        return self.text


class Entry(models.Model):
    """Информация, изцченная пользователем по теме"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "entries"

    def __str__(self):
        str_len = len(self.text)
        return self.text[:50] + "..." if str_len > 50 else self.text

learning_log/users/models.py
from django.db import models

# Create your models here.

learning_log/learning_logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': 'Name of new topic'}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_log/learning_logs/views.py
from django.shortcuts import render, get_object_or_404

from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm


def index(request):
    """Домашняя страница приложения Learning Log"""
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    """Выводит список всех тем"""
    # topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    """Выводит одну тему и все её записи"""
    topic = get_object_or_404(Topic, id=topic_id)
    # check_topic_owner(request, topic)
    entries = topic.entry_set.order_by("-date_added")
    context = {'topic': topic, 'entries': entries}
    return render(request, "learning_logs/topic.html", context)


@login_required
def new_topic(request):
    """Определяет новую тему"""
    if request.method != 'POST':
        # Данные не отправлялись, создается новая форма
        form = TopicForm()
    else:
        # Отправлены данные POST; обработать данные
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """Добавляет новую запись по конкретной теме"""
    topic = Topic.objects.get(id=topic_id)
    check_topic_owner(request, topic)

    if request.method != 'POST':
        # Данные не отправлялись, создается новая форма
        form = EntryForm()
    else:
        # Отправлены данные POST; обработать данные
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Редактирует существующую запись"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    check_topic_owner(request, topic)

    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными для текущей записи
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


def check_topic_owner(request, topic):
    if request.user != topic.owner:
        raise Http404

learning_log/users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm


def logout_view(request):
    """Завершает сеанс работы с приложением"""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))


def register(request):
    """Регистрирует нового пользователя"""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_log/learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="eng">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Learning Log</title>

        {% bootstrap_css %}
        {% bootstrap_javascript %}

    </head>
    <body>
        <!-- Статическая навигационная панель -->
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">

                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed"
                            data-toggle="collapse" data-target="#navbar"
                            aria-expanded="false" aria-controls="navbar">
                    </button>
                    <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
                        Learning Log
                    </a>
                </div>

                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'learning_logs:topics' %}">Topics</a> </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li><a>Hello, {{ user.username }}</a></li>
                            <li><a href="{% url 'users:logout' %}">Log out</a></li>
                        {% else %}
                            <li><a href="{% url 'users:register' %}">Register</a></li>
                            <li><a href="{% url 'users:login' %}">Log in</a></li>
                        {% endif %}
                    </ul>
                </div>

            </div>
        </nav>

        <div class="container">
            <div class="page-header">
                {% block header %}{% endblock header%}
            </div>
            <div>
                {% block content %}{% endblock content %}
            </div>
        </div>
    </body>
</html>

learning_log/learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}


{% block header %}
    <h2>Topic: <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h2>
{% endblock header %}

{% block content %}
    <h3>Edit entry:</h3>

    <form action="{% url 'learning_logs:edit_entry' entry.id %}" class="form" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
        <button name="submit" class="btn btn-primary">Save changes</button>
        {% endbuttons %}
    </form>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}
    <div class="jumbotron">
        <h1>Track your learning.</h1>
    </div>
{% endblock header %}

{% block content %}
    <h2>
        <a href="{% url 'users:register' %}">Register an account</a> to make
        your own Learning Log, and list the topics you're learning about.
    </h2>
    <h2>
        Whenever you learn something new about a topic, make an entry
        summarizing what you've learned.
    </h2>
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Topic: <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h2>
{% endblock header %}

{% block content %}
    <h3>Add a new entry:</h3>

    <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">Add entry</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h2>Add new topic:</h2>
{% endblock header %}

{% block content %}
    <form action="{% url 'learning_logs:new_topic' %}" class="form" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="Submit" class="btn btn-primary">Add topic</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Topic: {{ topic }}</h2>
{% endblock header %}

{% block content %}
    {% if request.user == topic.owner %}
        <form action="{% url 'learning_logs:new_entry' topic.id %}">
            {% buttons %}
                <button name="submit" class="btn btn-primary">Add new entry</button>
            {% endbuttons %}
        </form>
    {% endif %}

    {% for entry in entries %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>
                    {{ entry.date_added|date:'M d, Y H:i' }}
                    {% if request.user == topic.owner %}
                        <small>
                            <a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a>
                        </small>
                    {% endif %}
                </h3>
            </div>
            <div class="panel-body">
                {{ entry.text|linebreaks }}
            </div>
        </div>
    {% empty %}
        <h4>There are no entries for this topic yet.</h4>
    {% endfor %}
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Topics</h2>
{% endblock header %}

{% block content %}
    <ul class="list-group">
        {% for topic in topics %}
            <li class="list-group-item">
                <h3>
                    <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
                    {% if topic.owner == request.user %}
                        <span class="text-muted" style="font-style: italic; font-weight: lighter">
                            (My topic)
                        </span>
                    {% endif %}
                </h3>
            </li>
        {% empty %}
            <h4><li>No topics have been added yet.</li></h4>
        {% endfor %}
    </ul>

    <form action="{% url 'learning_logs:new_topic' %}">
        {% buttons %}
            <button name="submit" class="btn btn-primary">Add new topic</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_log/users/templates/users/login.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}
    <form method="post" action="{% url 'users:login' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="Submit" class="btn btn-primary">Log in</button>
        {% endbuttons %}

        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}"/>
    </form>
{% endblock content %}

learning_log/users/templates/users/register.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h2>Register your account.</h2>
{% endblock header %}

{% block content %}
    <form action="{% url 'users:register' %}" class="form" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="Submit" class="btn btn-primary">Register</button>
        {% endbuttons %}

        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}"/>
    </form>
{% endblock content %}