blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'), namespace="users")),
    path(r'', include(('blogs.urls', 'blogs'), namespace="blogs")),
]

blog/blogs/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add_post/$', views.add_post, name='add_post'),
    url(r'^(?P<post_id>\d+)/$', views.post, name='post'),
    url(r'^(?P<post_id>\d+)/edit_post/$', views.edit_post, name='edit_post'),
]

blog/users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login
from . import views


urlpatterns = [
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$', views.logout_view, name='logout'),
]

blog/blogs/models.py
from django.db import models


class BlogPost(models.Model):
    title = models.CharField(max_length=50)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

blog/users/models.py
from django.db import models

# Create your models here.

blog/blogs/forms.py
from django import forms
from .models import BlogPost


class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'text']
        labels = {'title': 'Title of post:', 'text': 'Description of post:'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

blog/blogs/views.py
from django.shortcuts import render
from .models import BlogPost
from .forms import BlogPostForm

from django.http import HttpResponseRedirect
from django.urls import reverse


def index(request):
    posts = BlogPost.objects.order_by('-date_added')
    context = {'posts': posts}
    return render(request, 'blogs/index.html', context)


def post(request, post_id):
    post = BlogPost.objects.get(id=post_id)
    context = {'post': post}
    return render(request, 'blogs/post.html', context)


def add_post(request):
    if request.method != 'POST':
        form = BlogPostForm()
    else:
        form = BlogPostForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('blogs:index'))
    context = {'form': form}
    return render(request, 'blogs/add_post.html', context)


def edit_post(request, post_id):
    post = BlogPost.objects.get(id=post_id)

    if request.method != 'POST':
        form = BlogPostForm(instance=post)
    else:
        form = BlogPostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('blogs:post', args=[post_id]))
    context = {'post': post, 'form': form}
    return render(request, 'blogs/edit_post.html', context)

blog/users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('blogs:index'))


def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('blogs:index'))
    context = {'form': form}
    return render(request, 'users/register.html', context)

blog/blogs/templates/blogs/add_post.html
{% extends 'blogs/base.html' %}

{% block content %}
    <p>Add new post:</p>

    <form action="{% url 'blogs:add_post' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add</button>
    </form>
{% endblock content %}

blog/blogs/templates/blogs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <a href="{% url 'blogs:index' %}">Home</a> -
    {% if user.is_authenticated %}
        Hello, {{ user.username }} -
        <a href="{% url 'users:logout' %}">Log out</a>
    {% else %}
        <a href="{% url 'users:register' %}">Register</a> -
        <a href="{% url 'users:login' %}">Log in</a>
    {% endif %}
</head>
<body>
    {% block content %}
    {% endblock content %}
</body>
</html>

blog/blogs/templates/blogs/edit_post.html
{% extends 'blogs/base.html' %}

{% block content %}
    <p>Edit post <i>"{{ post.title }}"</i>:</p>

    <form action="{% url 'blogs:edit_post' post.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Save changes</button>
    </form>
{% endblock content %}

blog/blogs/templates/blogs/index.html
{% extends 'blogs/base.html' %}

{% block content %}
    {% if posts %}
        <ul>
            {% for post in posts %}
                <li>
                <p><a href="{% url 'blogs:post' post.id %}">{{ post }}</a></p>
                <p>{{ post.date_added|date:'M d, Y H:i' }}</p>
                <br>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no posts yet.</p>
    {% endif %}
    <form action="{% url 'blogs:add_post' %}">
        <button name="submit">Add new post</button>
    </form>
{% endblock content %}

blog/blogs/templates/blogs/post.html
{% extends 'blogs/base.html' %}

{% block content %}
    <p>
        <b>{{ post.title }}</b> ({{ post.date_added|date:'M d, Y H:i' }})
    </p>
    <p>{{ post.text|linebreaks }}</p>
    <form action="{% url 'blogs:edit_post' post.id %}">
        <button name="submit">Edit post</button>
    </form>
{% endblock content %}

blog/users/templates/users/login.html
{% extends 'blogs/base.html' %}

{% block content %}
    {% if form.errors %}
        <p>Your username or password didn't match. Please try again.</p>
    {% endif %}

    <form method="post" action="{% url 'users:login' %}">
        {% csrf_token %}
        {{ form.as_p }}

        <button name="Submit">Log in</button>
        <input type="hidden" name="next" value="{% url 'blogs:index' %}"/>
    </form>

{% endblock content %}

blog/users/templates/users/register.html
{% extends 'blogs/base.html' %}

{% block content %}
    <form method="post" action="{% url 'users:register' %}">
        {% csrf_token %}
        {{ form.as_p }}

        <button name="Submit">Register</button>
        <input type="hidden" name="next" value="{% url 'blogs:index' %}"/>
    </form>

{% endblock content %}